platzzeiten:
  - mannschaft: Test Mannschaft
    tag: Mo - Fr
    uhrzeit: 15 - 22 Uhr
    platz: Kunstrasen
hallenzeiten:
  - mannschaft: Test Mannschaft
    tag: Mo - Fr
    uhrzeit: 16 - 20 Uhr
    halle: Mehrzweckhalle
